# Generated by Django 6.0.5 on 2026-05-20 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_recurringexpense'),
        ('expenses', '0004_seed_categories'),
    ]

    operations = [
    ]
